public class Sample7 {
    
    public void didplay(){
        
      
        Map < String, String > mapCustomer = new Map < String, String >();
mapCustomer.put('Sample', 'Value');
mapCustomer.put('Sample1', 'Value1');
mapCustomer.put('Sample2', 'Value2');
mapCustomer.put('Sample3', 'Value3');
mapCustomer.put('Sample4', '122');
for(String gg:mapCustomer.keySet())
system.debug(gg);
     
       
    }

}